### ISSUE TITLE
Code question of fmm_planner.py

### ISSUE THREAD

**Issue by rainbow979** [devendrachaplot/Neural-SLAM#10]
The function get_short_term_goal:
I don't understand why the code needs subset? 
I think this function is to find a minium distance to the global goal in a local zone, right?

**Comment by devendrachaplot** [comment]
The subset is used to find the short-term goal in an area around the agent. The short-term goal location is passed to the Local Policy for taking navigational actions. You can check the corresponding paper for details on the modules in the Active Neural SLAM model:

https://openreview.net/pdf?id=HklXn1BKDH
