### ISSUE TITLE
hello,i have a question about the folder location

### ISSUE THREAD

**Issue by CloudWave818** [devendrachaplot/Neural-SLAM#11]
Should I put the three folders side by side? Like this：
The folders/
     Neural-SLAM/
     habitat-api/
     habitat-sim/
Or，put 'habitat-api' and 'habitat-sim' in 'Neural-SLAM'?
Thank you.

**Comment by devendrachaplot** [comment]
You can put habitat-api and habitat-sim in any location, putting folders side by side should work fine.
