### ISSUE TITLE
ModuleNotFoundError: No module named 'habitat_sim._ext'

### ISSUE THREAD

**Issue by Sunnyzhr** [devendrachaplot/Neural-SLAM#12]
# Overview
When running `python main.py -n1 --auto_gpu_config 0 --split val`, I will get error if I write `~/.bashrc` with `export PYTHONPATH=$PYTHONPATH:~/Desktop/habitat-sim/`

> ModuleNotFoundError: No module named 'habitat_sim._ext'

I will also get error if I write `~/.bashrc` with `unset PYTHONPATH`

> ModuleNotFoundError: No module named habitat.sims.habitat_simulato.action_spaces'

# My Info
ENVIRONMENT INFO:
Platform: Linux-5.4.0-52-generic-x86_64-with-glibc2.10
Machine: x86_64
Processor: x86_64
Libc version: glibc 2.27
Mac version: 
Python version: 3.8.3
Architecture: 64bit ELF
Win version:    
System OS: Linux
Release: 5.4.0-52-generic
Version: #57 18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020
Operational System: linux
GCC version: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0\n'
CMAKE version: 3.14.0
NVIDIA-SMI: Mon Oct 26 12:50:01 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1650    Off  | 00000000:01:00.0  On |                  N/A |
| N/A   42C    P8     3W /  N/A |    433MiB /  3903MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1323      G   /usr/lib/xorg/Xorg                 18MiB |
|    0   N/A  N/A      1413      G   /usr/bin/gnome-shell               47MiB |
|    0   N/A  N/A      1688      G   /usr/lib/xorg/Xorg                148MiB |
|    0   N/A  N/A      1827      G   /usr/bin/gnome-shell              134MiB |
|    0   N/A  N/A      3226      G   /usr/lib/firefox/firefox            1MiB |
|    0   N/A  N/A     31858      G   ...AAAAAAAAA= --shared-files       79MiB |
+-----------------------------------------------------------------------------+

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0

# My Steps

1.Git clone
```
cd ~/Desktop
git clone --branch stable https://github.com/facebookresearch/habitat-sim.git
git clone --branch stable https://github.com/facebookresearch/habitat-lab.git
git clone --recurse-submodules https://github.com/devendrachaplot/Neural-SLAM

sudo chmod 777 -R ~/Desktop/habitat-sim
sudo chmod 777 -R ~/Desktop/habitat-lab
sudo chmod 777 -R ~/Desktop/Neural-SLAM
```
2.conda install
Instructed by [habitat-sim tutorials](https://github.com/facebookresearch/habitat-sim)

```
cd ~/Desktop/habitat-sim
conda install habitat-sim -c conda-forge -c aihabitat
conda install habitat-sim headless -c conda-forge -c aihabitat
conda install habitat-sim withbullet headless -c conda-forge -c aihabitat

cd ~/Desktop/habitat-lab
conda install habitat-sim -c conda-forge -c aihabitat
conda install habitat-sim headless -c conda-forge -c aihabitat
conda install habitat-sim withbullet headless -c conda-forge -c aihabitat

cd ~/Desktop/Neural-SLAM
conda install habitat-sim -c conda-forge -c aihabitat
conda install habitat-sim headless -c conda-forge -c aihabitat
conda install habitat-sim withbullet headless -c conda-forge -c aihabitat
```
3.build habitat-sim
Instructed by  [BuildFromSource:](https://github.com/facebookresearch/habitat-sim/blob/master/BUILD_FROM_SOURCE.md)

```
cd ~/Desktop/habitat-sim
conda create -n habitat python=3.6 cmake=3.14.0

conda activate habitat
pip install -r requirements.txt
sudo apt-get update || true
sudo apt-get install -y --no-install-recommends \
     libjpeg-dev libglm-dev libgl1-mesa-glx libegl1-mesa-dev mesa-utils xorg-dev freeglut3-dev

python setup.py install
python setup.py install --headless
python setup.py install --with-cuda
sudo apt-get install libbullet-dev
python setup.py install --bullet 
```
All these bulid commands above run successfully.
```
./build/viewer ./data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
./build/viewer --enable-physics ./data/scene_datasets/habitat-test-scenes/van-gogh-room.glb
python examples/example.py --scene ./data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
python examples/example.py --scene ./data/scene_datasets/habitat-test-scenes/skokloster-castle.glb --enable_physics
```
All these example files above run successfully.

4.export PATHONPATH
**This is the most confusing part. I really have no idea what to do.**
Instructed by  [BuildFromSource:](https://github.com/facebookresearch/habitat-sim/blob/master/BUILD_FROM_SOURCE.md), we should write `~/.bashrc` with `export PYTHONPATH=$PYTHONPATH:~/Desktop/habitat-sim/` However, after doing that, I even could not succeed run example file of habitat-sim, and will get error:
> ModuleNotFoundError: No module named 'habitat_sim._ext'

Then accoriding to[ erikwijmans commented on Feb 14,](https://github.com/facebookresearch/habitat-sim/issues/491) 
>Please do unset PYTHONPATH (or similar) to remove it.

Then I write `~/.bashrc` with `unset PYTHONPATH`. I can succeed to run example files of habitat-sim again.

5. build habitat-lab
```
sudo -s
conda activate habitat
cd ~/Desktop/habitat-lab
pip install -e .
pip install -r requirements.txt
python setup.py develop --all

python examples/example.py 
python setup.py test
python examples/benchmark.py
```
I can successfully bulid and run the example files.

6.build Neural-SLAM
```
sudo -s 
conda activate habitat
cd ~/Desktop/Neural-SLAM
conda install pytorch==1.2.0 torchvision cudatoolkit=11.0 -c pytorch
```
I will get error:

> (Error: habitat 0.1.6 requires torch>=1.3.1, but you'll have torch 1.2.0 which is incompatible.)

I ignore it and  run next commands:`pip install -r requirements.txt`**(I don't whether I need to upgrade the torch version to 1.3.1)**

Then, when run command `python main.py -n1 --auto_gpu_config 0 --split val`, I get error:

> ModuleNotFoundError: No module named habitat.sims.habitat_simulato.action_spaces'

It should be noticed that, at that time, I wrote `~/.bashrc` with `unset PYTHONPATH`. 
Thus, I try to write `~/.bashrc` with `export PYTHONPATH=$PYTHONPATH:~/Desktop/habitat-sim/` , then the error will change to:

> ModuleNotFoundError: No module named 'habitat_sim._ext'

So what is the correct PYTHONPATH to add in to `~/.bashrc` ?
How to fix the error?

# Expectation
Successfully run the code.

**Comment by Sunnyzhr** [comment]
I delete all files, and re-download the entire folder.  When running `(habitat) root@c:~/Desktop/Neural-SLAM# python main.py -n1 --auto_gpu_config 0 --split val
` again, I get different error:

> Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from env import make_vec_envs
  File "/home/u/Desktop/Neural-SLAM/env/__init__.py", line 3, in <module>
    from .habitat import construct_envs
  File "/home/u/Desktop/Neural-SLAM/env/habitat/__init__.py", line 9, in <module>
    from .exploration_env import Exploration_Env
  File "/home/u/Desktop/Neural-SLAM/env/habitat/exploration_env.py", line 14, in <module>
    from torchvision import transforms
ModuleNotFoundError: No module named 'torchvision'

This time, ModuleNotFoundError changes from 'gym' to 'torchvision'. Then I try to `(habitat) root@c:~/Desktop/Neural-SLAM# conda install torchvision
` and run `(habitat) root@c:~/Desktop/Neural-SLAM# python main.py -n1 --auto_gpu_config 0 --split val
` again. I get the error below:

> ModuleNotFoundError: No module named 'habitat.sims.habitat_simulator.action_spaces'


How to solve these ModuleNotFoundErrors?

**Comment by devendrachaplot** [comment]
Hi,
You need to install specific older versions of habitat-sim and habitat-api for running the Active Neural SLAM code. Check the instructions on installing dependencies in the README for specific versions:

https://github.com/devendrachaplot/Neural-SLAM/blob/master/README.md#installing-dependencies

**Comment by Sunnyzhr** [comment]
@devendrachaplot Thanks for reply!
I follow the instructions, but still get a little trouble:

# My Steps (before Error)
0. Preparations
Intructed by [BuildFromSource](https://github.com/facebookresearch/habitat-sim/blob/master/BUILD_FROM_SOURCE.md)
```
sudo -s
conda create -n habitat python=3.6 cmake=3.14.0
conda activate habitat
sudo apt-get update || true
sudo apt-get install -y --no-install-recommends \
     libjpeg-dev libglm-dev libgl1-mesa-glx libegl1-mesa-dev mesa-utils xorg-dev freeglut3-dev
```
1. Installing habitat-sim
Instructed by [ActiveNeuralSLAM](https://github.com/devendrachaplot/Neural-SLAM)
```
cd ~/Desktop
git clone https://github.com/facebookresearch/habitat-sim.git
cd habitat-sim; git checkout 9575dcd45fe6f55d2a44043833af08972a7895a9; 
```
**The checkout information** is as below:

> (habitat) root@c:~/Desktop# cd habitat-sim; git checkout 9575dcd45fe6f55d2a44043833af08972a7895a9; 
> Note: checking out '9575dcd45fe6f55d2a44043833af08972a7895a9'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> HEAD is now at 9575dcd Bullet Physics Integration #1 (#91)

```
pip install -r requirements.txt; 
```
I get **a warning**:

> (habitat) root@c:~/Desktop/habitat-sim# pip install -r requirements.txt; 
> **WARNING**: The directory '/home/u/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> 

```
python setup.py install --headless
```
I get the same **warning**:
> Using /home/u/anaconda3/envs/habitat/lib/python3.6/site-packages
> Finished processing dependencies for habitat-sim==0.1.2
> **WARNING:** The directory '/home/u/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Processing ./build/deps/magnum-bindings/src/python
> Building wheels for collected packages: magnum
>   Building wheel for magnum (setup.py) ... done
>   Created wheel for magnum: filename=magnum-0.0.0-cp36-cp36m-linux_x86_64.whl size=1310443 sha256=d5590e83d54bc3a439f78670780bc949dc9fde561942b2aec0de69a5bc732bb7
>   Stored in directory: /tmp/pip-ephem-wheel-cache-q697ojl2/wheels/31/f6/f6/24e2dea66d597afa365ec31feb5ef879b12b7e448712ffaa0d
> Successfully built magnum
> Installing collected packages: magnum
> Successfully installed magnum-0.0.0

2. Installing habitat-api:
Instructed by [ActiveNeuralSLAM](https://github.com/devendrachaplot/Neural-SLAM)
```
cd ~/Desktop
git clone https://github.com/facebookresearch/habitat-api.git
cd habitat-api; git checkout b5f2b00a25627ecb52b43b13ea96b05998d9a121; 
```
The checkout information is as below:
> (habitat) root@c:~/Desktop# cd habitat-api; git checkout b5f2b00a25627ecb52b43b13ea96b05998d9a121;
> Note: checking out 'b5f2b00a25627ecb52b43b13ea96b05998d9a121'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> # Overview
> HEAD is now at b5f2b00 Correct the naming of PointGoalNav Sensors (#180)
```
pip install -e .

```
3. Installing pytorch
```
conda install pytorch==1.2.0 torchvision cudatoolkit=11.0 -c pytorch
```
**I install the 11.0 version instead of 10.0 because my cuda is 11.0. I don't know whether it will have bad effect.**

Also, the result of following commands is `False`, does it matter?
```
python
import torch
torch.cuda.is_available()
```
4. Setup
```
cd ~/Desktop
git clone --recurse-submodules https://github.com/devendrachaplot/Neural-SLAM
```
Running `git clone` command I get the information below. As you see there is a checkout information **`8ac1b16aa0554b10748a925f8a937954c77c1563`.** **However **I cannot `git checkout` it** neither in `~/Desktop` or in `~/Desktop/Neural-SLAM`.**  and get `fatal: reference is not a tree: 8ac1b16aa0554b10748a925f8a937954c77c1563`
 Does it matter?
> (habitat) root@c:~/Desktop# git clone --recurse-submodules https://github.com/devendrachaplot/Neural-SLAM
> Cloning into 'Neural-SLAM'...
> remote: Enumerating objects: 50, done.
> remote: Total 50 (delta 0), reused 0 (delta 0), pack-reused 50
> Unpacking objects: 100% (50/50), done.
> Submodule 'env/habitat/habitat_api' (https://github.com/devendrachaplot/habitat-api) registered for path 'env/habitat/habitat_api'
> Cloning into '/home/u/Desktop/Neural-SLAM/env/habitat/habitat_api'...
> remote: Enumerating objects: 2824, done.        
> remote: Total 2824 (delta 0), reused 0 (delta 0), pack-reused 2824        
> Receiving objects: 100% (2824/2824), 27.98 MiB | 5.77 MiB/s, done.
> Resolving deltas: 100% (1811/1811), done.
> Submodule path 'env/habitat/habitat_api': checked out '**8ac1b16aa0554b10748a925f8a937954c77c1563**'
> 

```
cd Neural-SLAM;
pip install -r requirements.txt
```
Up to this step, I only get warnings without error.

# Error
At first, I try to remove the lock of my folders.
```
sudo chmod 777 -R ~/Desktop/habitat-sim
sudo chmod 777 -R ~/Desktop/habitat-api
sudo chmod 777 -R ~/Desktop/Neural-SLAM
```
Then I try to run `python main.py -n1 --auto_gpu_config 0 --split val`. I will get error. Let me introduce in three situation:
Situation-1: If I write `~/.bashrc` with `unset PYTHONPATH`:
> (habitat) root@c:~/Desktop/Neural-SLAM# python main.py -n1 --auto_gpu_config 0 --split val
> Traceback (most recent call last):
>   File "main.py", line 15, in <module>
>     from env import make_vec_envs# Overview
>   File "/home/u/Desktop/Neural-SLAM/env/__init__.py", line 3, in <module>
>     from .habitat import construct_envs
>   File "/home/u/Desktop/Neural-SLAM/env/habitat/__init__.py", line 9, in <module>
>     from .exploration_env import Exploration_Env
>   File "/home/u/Desktop/Neural-SLAM/env/habitat/exploration_env.py", line 29, in <module>
>     import env.habitat.utils.pose as pu
> AttributeError: module 'env' has no attribute 'habitat'
> 
Situation-2: If I write `~/.bashrc` with `export PYTHONPATH=$PYTHONPATH:~/Desktop/habitat-sim/`:
> (habitat) root@c:~/Desktop/Neural-SLAM# python main.py -n1 --auto_gpu_config 0 --split val
> Traceback (most recent call last):
>   File "main.py", line 15, in <module>
>     from env import make_vec_envs
>   File "/home/u/Desktop/Neural-SLAM/env/__init__.py", line 3, in <module>
>     from .habitat import construct_envs
>   File "/home/u/Desktop/Neural-SLAM/env/habitat/__init__.py", line 9, in <module>
>     from .exploration_env import Exploration_Env
>   File "/home/u/Desktop/Neural-SLAM/env/habitat/exploration_env.py", line 28, in <module>
>     from env.habitat.utils.noisy_actions import CustomActionSpaceConfiguration
>   File "/home/u/Desktop/Neural-SLAM/env/habitat/utils/noisy_actions.py", line 5, in <module>
>     import habitat_sim
>   File "/home/u/Desktop/habitat-sim/habitat_sim/__init__.py", line 12, in <module>
>     from .nav import *
>   File "/home/u/Desktop/habitat-sim/habitat_sim/nav/__init__.py", line 1, in <module>
>     from .greedy_geodesic_follower import GreedyGeodesicFollower
>   File "/home/u/Desktop/habitat-sim/habitat_sim/nav/greedy_geodesic_follower.py", line 6, in <module>
>     import habitat_sim.agent
>   File "/home/u/Desktop/habitat-sim/habitat_sim/agent/__init__.py", line 7, in <module>
>     from .agent import *
>   File "/home/u/Desktop/habitat-sim/habitat_sim/agent/agent.py", line 14, in <module>
>     import habitat_sim.bindings as hsim
>   File "/home/u/Desktop/habitat-sim/habitat_sim/bindings/__init__.py", line 24, in <module>
>     from habitat_sim._ext.habitat_sim_bindings import Simulator as SimulatorBackend
> ModuleNotFoundError: No module named 'habitat_sim._ext'
> 
Situation-3: If I write `~/.bashrc` without any extra code:
> (habitat) root@c:~/Desktop/Neural-SLAM# python main.py -n1 --auto_gpu_config 0 --split val
> Traceback (most recent call last):
>   File "main.py", line 15, in <module>
>     from env import make_vec_envs
>   File "/home/u/Desktop/Neural-SLAM/env/__init__.py", line 3, in <module>
>     from .habitat import construct_envs
>   File "/home/u/Desktop/Neural-SLAM/env/habitat/__init__.py", line 9, in <module>
>     from .exploration_env import Exploration_Env
>   File "/home/u/Desktop/Neural-SLAM/env/habitat/exploration_env.py", line 29, in <module>
>     import env.habitat.utils.pose as pu
> AttributeError: module 'env' has no attribute 'habitat'
> 

So, what should I write in `~/.bashrc`? And how to fix the problem? 

**Thank you very much for reading!**
# Expectation
Successfully run the codes.

**Comment by Sunnyzhr** [comment]
@devendrachaplot Thank you so much for reply!

I follow your instructions carefully, and encounter another error`AttributeError: module 'env' has no attribute 'habitat'`. Fortunately, I follow [your instruction](https://github.com/devendrachaplot/Neural-SLAM/issues/1) again to solve the problem. (By change `import ...` to `from ... import ...` ) THANKS again!!!

After that, I encounter another trouble that I cannot run with GPU. I fix it by change my torch(cuda11.0) to torch(cuda10.0).

Then, I start to run commands of the tutorial, I've encounter several new problems as below:
## New problem 1 - `python main.py -n1 --auto_gpu_config 0 --split val`
The command runs without error at the first 38 minuets. However, then it encounter errors as below. Additionally, I find that there are some other [people who encouter the same error](https://blog.csdn.net/xyt723916/article/details/109284565). **The code will fail at `Cantwell.glb`**
> ...
> ...
> Time: 00d 00h 37m 49s, num timesteps 980, FPS 0,
> 	Rewards:
> 	Losses: Local Loss: 4.630, SLAM Loss proj/exp/pose:0.0004/0.0004/0.0101
> Time: 00d 00h 38m 11s, num timesteps 990, FPS 0,
> 	Rewards:
> 	Losses: Local Loss: 4.661, SLAM Loss proj/exp/pose:0.0003/0.0003/0.0100
> 2020-10-27 17:39:42,208 **Computing map for data/scene_datasets/gibson/Cantwell.glb**
> Traceback (most recent call last):
>   File "main.py", line 769, in <module>
>     main()
>   File "main.py", line 617, in main
>     g_agent.update(g_rollouts)
>   File "/home/u/Desktop/Neural-SLAM/algo/ppo.py", line 58, in update
>     for sample in data_generator:
>   File "/home/u/Desktop/Neural-SLAM/utils/storage.py", line 95, in feed_forward_generator
>     mini_batch_size = batch_size // num_mini_batch
> ZeroDivisionError: integer division or modulo by zero
> Exception ignored in: <bound method VectorEnv.__del__ of <env.habitat.habitat_api.habitat.core.vector_env.VectorEnv object at 0x7faf77d21c18>>
> Traceback (most recent call last):
>   File "/home/u/Desktop/Neural-SLAM/env/habitat/habitat_api/habitat/core/vector_env.py", line 487, in __del__
>     self.close()
>   File "/home/u/Desktop/Neural-SLAM/env/habitat/habitat_api/habitat/core/vector_env.py", line 351, in close
>     write_fn((CLOSE_COMMAND, None))
>   File "/home/u/anaconda3/envs/habitat/lib/python3.6/multiprocessing/connection.py", line 206, in send
>     self._send_bytes(_ForkingPickler.dumps(obj))
>   File "/home/u/anaconda3/envs/habitat/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
>     self._send(header + buf)
>   File "/home/u/anaconda3/envs/habitat/lib/python3.6/multiprocessing/connection.py", line 368, in _send
>     n = write(self._handle, buf)
> BrokenPipeError: [Errno 32] Broken pipe

## New problem 2 - `python main.py`
The error information is:

> (habitat) root@c:~/Desktop/Neural-SLAM# python main.py
> Traceback (most recent call last):
>   File "main.py", line 33, in <module>
>     args = get_args()
>   File "/home/u/Desktop/Neural-SLAM/arguments.py", line 198, in get_args
>     /1024/1024/1024 > 10.0, "Insufficient GPU memory"
> AssertionError: Insufficient GPU memory

I check my GPU memory (I only have 1 GPU) with `torch.cuda.get_device_properties(0).total_memory/1024/1024/1024` . The result is `
 3.81195068359375` which is less than 10. 
I see the [arguments.py](https://github.com/devendrachaplot/Neural-SLAM/blob/master/arguments.py), there are two lines: 
> num_processes_per_gpu = int(gpu_memory/1.4)
> num_processes_on_first_gpu = int((gpu_memory - 10.0)/1.4)

Therefore, **could you please recommend me a value of `num_processes_per_gpu` and `num_processes_on_first_gpu`?**

# Expectation
Successfully run the codes.

Thanks for your attention!
