### ISSUE TITLE
Helpful information about the local policy model?

### ISSUE THREAD

**Issue by Singh-sid930** [devendrachaplot/Neural-SLAM#14]
Hi, 
Just wanted some implementation clarity on the local policy model. 
1. I am assuming the images provided to the local policy are normalized? Correct me if I am wrong. 
2. I notice that there is a remapping for action spaces. For the local policy pretrained model is the action space prediction : [left,right,forward] ? 
3. the angles provided to the local policy model are in the global frame?

**Comment by devendrachaplot** [comment]
Hi,
1. The images provided to the local policy are not normalized.
2. Yes, that's correct.
3. The angles provided to the local policy are relative to the agent's orientation.
