### ISSUE TITLE
About "Demo videos: PointGoal"

### ISSUE THREAD

**Issue by CloudWave818** [devendrachaplot/Neural-SLAM#15]
Hello, "Demo videos: Exploration and PointGoal" is displayed on your website. How do I run "Demo videos: PointGoal"? Thanks for the help.

**Comment by devendrachaplot** [comment]
Hi,
This repository does not contain the code for PointGoal transfer, you can take a look at this thread on how to add PointGoal transfer to the code:
https://github.com/devendrachaplot/Neural-SLAM/issues/4

**Comment by CloudWave818** [comment]
> Hi,
> This repository does not contain the code for PointGoal transfer, you can take a look at this thread on how to add PointGoal transfer to the code:
> #4

Thank you
