### ISSUE TITLE
How do the visualization part work

### ISSUE THREAD

**Issue by QieSima** [devendrachaplot/Neural-SLAM#28]
Hello! I am curious about the visualization of your project especially the generation of map with exploring trajectory like the gif in your website. I look through the code and didn't find how the visualization part works. Could you give me some hints?
By the way, could you tell how much time did you spend in training and how many GPUs you have used ? Thanks!

**Comment by devendrachaplot** [comment]
For visualization, just add `-v 1` argument to the run command, see instructions here:
https://github.com/devendrachaplot/Neural-SLAM#for-evaluation

The visualization code is in this file:
https://github.com/devendrachaplot/Neural-SLAM/blob/master/env/habitat/utils/visualizations.py

We trained the model with 72 parallel threads on an 8-GPU system for 10 million frames. The amount of time varies from system to system, depending on the number of GPUs you use and GPU & CPU speeds.
