### ISSUE TITLE
Moncular visual SLAM

### ISSUE THREAD

**Issue by Zumbalamambo** [devendrachaplot/Neural-SLAM#3]
Is this monocular visual slam based on rgb data? How do I prepare a custom dataset?

**Comment by devendrachaplot** [comment]
Hi,
Yes, this is monocular visual slam based on RGB data. You will require ground truth depth and pose for training the Neural SLAM module. Check lines 379 to 397 in main.py for data format and lines 541 to 582 in main.py for training code.

**Comment by Zumbalamambo** [comment]
@devendrachaplot How do I prepare a custom dataset? May I know what sensory readings refers to?
