### ISSUE TITLE
Resources required to train a good model

### ISSUE THREAD

**Issue by haokuanluo** [devendrachaplot/Neural-SLAM#30]
Hi,

I have used one GPU for the training of the model, and it is able to take about 100,000 (0.1 million) steps per 24 hours. This is far from the 10 million steps mentioned in the paper, and I am wondering whether I made any mistakes in my training procedure. How many GPUs did you use for training, and how long did you train the agent to reach 10 million steps? Thanks!

**Comment by devendrachaplot** [comment]
Hi,
We trained the model with 72 parallel threads on a system with 8 Nvidia V100 GPUs for 10 million steps, which takes around 24 hrs.
