### ISSUE TITLE
Training each module individually

### ISSUE THREAD

**Issue by vincent341** [devendrachaplot/Neural-SLAM#33]
Hello. It seems that the method consists of Neural Slam module (NS), global policy module(GP) and local policy module (LP). They are trained simultaneously. Would you mind letting me know if it is possible to train each of them individually?
For example,  firstly train the Neural Slam module. Then freeze it and train GP.  At last train LP while freezing NS and GP. It seems that training individually is relatively easy to fine tune. What's the advantage of training the three modules simultaneously compared with individually?

Your response would be highly appreciated.

**Comment by devendrachaplot** [comment]
We have not tried training each module individually. I do not know what way is better, but I would guess either way should not affect the final performance too much.
