### ISSUE TITLE
Sorry to ask question about `Neural Topological  SLAM for Visual Navigation`

### ISSUE THREAD

**Issue by KaninchenM** [devendrachaplot/Neural-SLAM#37]
Sorry to ask question about your paper `Neural Topological  SLAM for Visual Navigation` here because I didn't find NTSlam's github and didn't get connection with you by email.
Will the code of NTSlam be released later? Does any data or training code of your public projects `Object-Goal-Navigation` and `Neural-SLAM` shall I use to implement the `Neural Topological  SLAM`?
Hope to get your reply.

**Comment by devendrachaplot** [comment]
There's code released for our newer Image Goal Navigation project here:
https://github.com/meera1hahn/NRNS/

**Comment by KaninchenM** [comment]
您的邮件已收到，我会尽快回复您！

**Comment by KaninchenM** [comment]
您的邮件已收到，我会尽快回复您！
