### ISSUE TITLE
Question regarding MapBuilder 

### ISSUE THREAD

**Issue by zxwang96** [devendrachaplot/Neural-SLAM#42]
Hi,

I have some questions regarding the update_map method of MapBuilder class. When I plot the info['fp_proj'] and info['fp_explored'], like the image I post below, I found depth cam scanning shape is wired. I assume the shape should be like an isosceles triangle or trapezoid, but in the image you can see it's more like a half-triangle or half-trapezoid(right-half image shows nothing). Can you explain this to me?
![Figure_1](https://user-images.githubusercontent.com/28090369/125402961-96c5e900-e37a-11eb-9236-d932f80950ca.png)

Thank you!

**Comment by devendrachaplot** [comment]
The visualization seems correct to me. The agent is at the top center of the fp_proj and fp_explored visualization looking downward.
