### ISSUE TITLE
Question regarding sim_location preprocessing

### ISSUE THREAD

**Issue by wzx16** [devendrachaplot/Neural-SLAM#46]
Hi,

I have a question regarding the preprocessing method of sim location.
https://github.com/devendrachaplot/Neural-SLAM/blob/8876e1eafff5414e92d72347d89488d970a4f6b2/env/habitat/exploration_env.py#L372-L373
As I know the agent_state.position is ordered as (x,y,z) instead of (z, y, x). I wonder the reason for swapping x and y, and using their negative value? i.e. why it's not something like:
`x = agent_state.position[0]`
`y = agent_state.position[2]`

Thank you so much!

**Comment by zxwang96** [comment]
And may I know if I know the rel_pose_change on our custom coordinate system, how to use it to find the corresponding position on habitat-sim coordinate system?
