### ISSUE TITLE
How to apply the Neural-SLAM on VLN? 

### ISSUE THREAD

**Issue by ZhuFengdaaa** [devendrachaplot/Neural-SLAM#5]
I notice that your Nerual-SLAM method achieves the state-of-the art on VLN benchmark (on SPL). Congratulations! 

I have read your code I find that it is not easy to transfer the habitat implementation to Matterport environment. Especially the navigation graph is quite different from the 2D map. Could you please give me some hints about how to run Neural-SLAM in Matterport environment? Is it related to the paper "Neural Topological SLAM for Visual Navigation"?

**Comment by devendrachaplot** [comment]
Hi,
We did not submit our model to the VLN benchmark. Perhaps some other group has submitted the Active Neural SLAM model for the VLN benchmark.

It's easy to transfer the model to the Matterport dataset by just changing the dataset in the config file in Habitat. Unfortunately, I can not help you with the transfer to the VLN task as I am not familiar with the details of the navigation graph in the VLN task.
