### ISSUE TITLE
parameter order when calling atan2() seems wrong

### ISSUE THREAD

**Issue by limuyiju** [devendrachaplot/Neural-SLAM#50]
https://github.com/devendrachaplot/Neural-SLAM/blob/8876e1eafff5414e92d72347d89488d970a4f6b2/env/habitat/exploration_env.py#L495

The library function is: math.atan2(y, x)
But the usage here seems math.atan2(x, y)
Should the parameters x/y order be changed?

**Comment by devendrachaplot** [comment]
The usage is correct, it depends on how x and y axis are used in mapping for spatial transformation.
