### ISSUE TITLE
Distorted output

### ISSUE THREAD

**Issue by asfandasfo** [devendrachaplot/Neural-SLAM#53]
Hi, I was trying the Neural-SLAM with pre-trained models but I am getting distorted output (attached) from the camera. what could be the problem?
![0-1-Vis-107](https://user-images.githubusercontent.com/11736209/165524321-1d9abe60-3f32-4d35-9330-90e805d1f491.png)

**Comment by devendrachaplot** [comment]
The output looks correct to me.
