### ISSUE TITLE
No module named 'env.habitat.habitat_api.habitat'

### ISSUE THREAD

**Issue by Derry-Xing** [devendrachaplot/Neural-SLAM#54]
Installing collected packages: habitat
  Attempting uninstall: habitat
    Found existing installation: habitat 0.1.2
    Uninstalling habitat-0.1.2:
      Successfully uninstalled habitat-0.1.2
  Running setup.py develop for habitat
Successfully installed habitat-0.1.2
(habitat2) [20481535@scigpu15 habitat-api]$ cd ..
(habitat2) [20481535@scigpu15 Neural-SLAM]$ python main.py
/home/comp/20481535/enter/envs/habitat2/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator GaussianMixture from version 0.22.2.post1 when using version 1.1.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from env import make_vec_envs
  File "/home/comp/20481535/Neural-SLAM/env/__init__.py", line 3, in <module>
    from .habitat import construct_envs
  File "/home/comp/20481535/Neural-SLAM/env/habitat/__init__.py", line 10, in <module>
    from .habitat_api.habitat.core.vector_env import VectorEnv
ModuleNotFoundError: No module named 'env.habitat.habitat_api.habitat'

**Comment by devendrachaplot** [comment]
This might be the same issue with python 3.6 as mentioned in this thread:
https://github.com/devendrachaplot/Neural-SLAM/issues/1
