### ISSUE TITLE
Code questions

### ISSUE THREAD

**Issue by rainbow979** [devendrachaplot/Neural-SLAM#7]
What does this code(*filter(bool, [])) mean?
`self.conv = nn.Sequential(*filter(bool, [
            nn.Conv2d(512, 64, (1, 1), stride=(1, 1)),
            nn.ReLU()
        ]))`
https://github.com/devendrachaplot/Neural-SLAM/blob/master/model.py#L80

**Comment by devendrachaplot** [comment]
(*filter(bool, [x])) removes None layers in x. For example, if the block was the following:
```
self.conv = nn.Sequential(*filter(bool, [
            nn.Conv2d(512, 64, (1, 1), stride=(1, 1)),
            nn.ReLU() if args.use_relu else None,
        ]))
```

Here, I believe the filter would remove None layers if args.use_relu was False. 

It is redundant in the referred line, you can ignore it.
